version: '3.3'

networks:
    frontend:
    backend:

volumes:
    dbdata:

services:
    web:
        build:
            context: ./client
            dockerfile: Dockerfile.client
        volumes:
            - ./client/src:/usr/src/client
        networks:
            - frontend
        ports:
            - 8080:8080
    api:
        build:
            context: ./api
            dockerfile: Dockerfile.api
        networks:
            - frontend
            - backend
        ports:
            - 8000:8000
        volumes:
            - ./api/src:/usr/src/api/src
        environment:
            - PGHOST=db
            - PGUSER=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=password
    db:
        image: postgres
        networks:
            - backend
        environment:
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data
        volumes:
            - dbdata:/var/lib/postgresql/data

