version: '3.3'

networks:
    frontend:
    backend:

services:
    api:
        build:
            context: ./api
        networks:
            - frontend
            - backend
        environment:
            - PGHOST=db
            - PGUSER=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=password
    db:
        image: postgres
        networks:
            - backend
        environment:
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data

